DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20180805141449');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20180805141449');
-- Add your query below.

DROP TABLE IF EXISTS `npc_trainer_greeting`;
CREATE TABLE `npc_trainer_greeting` (
  `entry` int(11) unsigned NOT NULL DEFAULT 0,
  `content_default` text NOT NULL,
  `content_loc1` text DEFAULT NULL,
  `content_loc2` text DEFAULT NULL,
  `content_loc3` text DEFAULT NULL,
  `content_loc4` text DEFAULT NULL,
  `content_loc5` text DEFAULT NULL,
  `content_loc6` text DEFAULT NULL,
  `content_loc7` text DEFAULT NULL,
  `content_loc8` text DEFAULT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DELETE FROM `npc_trainer_greeting` WHERE `entry` IN
(198,
328,
331,
375,
376,
377,
459,
460,
461,
514,
543,
812,
837,
895,
906,
908,
911,
912,
913,
914,
915,
916,
917,
918,
925,
926,
927,
928,
944,
985,
986,
987,
988,
1103,
1215,
1218,
1226,
1228,
1229,
1231,
1232,
1234,
1241,
1292,
1300,
1317,
1346,
1355,
1382,
1385,
1386,
1404,
1411,
1430,
1458,
1470,
1473,
1632,
1651,
1676,
1680,
1681,
1683,
1699,
1700,
1701,
1702,
1703,
1901,
2114,
2119,
2122,
2123,
2124,
2126,
2127,
2128,
2129,
2130,
2131,
2132,
2326,
2327,
2329,
2367,
2390,
2391,
2399,
2485,
2489,
2492,
2627,
2704,
2798,
2818,
2834,
2836,
2837,
2855,
2856,
2878,
2879,
2998,
3001,
3004,
3007,
3009,
3011,
3013,
3026,
3028,
3030,
3031,
3032,
3033,
3034,
3036,
3038,
3039,
3040,
3041,
3042,
3043,
3044,
3045,
3046,
3047,
3048,
3049,
3059,
3060,
3061,
3062,
3063,
3064,
3065,
3066,
3067,
3069,
3087,
3136,
3137,
3153,
3154,
3155,
3156,
3157,
3169,
3170,
3171,
3172,
3173,
3174,
3175,
3179,
3181,
3184,
3185,
3290,
3306,
3324,
3325,
3326,
3327,
3328,
3332,
3344,
3345,
3347,
3352,
3353,
3354,
3355,
3357,
3363,
3365,
3373,
3399,
3401,
3403,
3404,
3406,
3407,
3408,
3478,
3484,
3494,
3523,
3545,
3549,
3555,
3557,
3593,
3594,
3595,
3596,
3597,
3598,
3599,
3600,
3601,
3602,
3603,
3604,
3605,
3606,
3607,
3620,
3622,
3624,
3688,
3690,
3698,
3703,
3704,
3706,
3707,
3963,
3964,
3965,
3967,
4087,
4089,
4090,
4091,
4092,
4138,
4146,
4156,
4159,
4160,
4163,
4165,
4193,
4204,
4205,
4210,
4211,
4212,
4213,
4214,
4215,
4217,
4218,
4219,
4254,
4258,
4320,
4552,
4563,
4564,
4565,
4566,
4567,
4568,
4573,
4576,
4578,
4582,
4583,
4584,
4588,
4591,
4593,
4594,
4595,
4596,
4598,
4606,
4607,
4608,
4611,
4614,
4616,
4732,
4752,
4753,
4772,
4773,
4898,
4900,
5032,
5037,
5038,
5040,
5041,
5113,
5114,
5115,
5116,
5117,
5127,
5137,
5141,
5142,
5143,
5144,
5145,
5146,
5147,
5148,
5149,
5150,
5153,
5157,
5159,
5161,
5164,
5165,
5166,
5167,
5171,
5172,
5173,
5174,
5177,
5392,
5479,
5480,
5482,
5484,
5489,
5491,
5492,
5493,
5495,
5496,
5497,
5498,
5499,
5501,
5502,
5504,
5505,
5506,
5511,
5513,
5515,
5516,
5517,
5518,
5564,
5566,
5612,
5690,
5695,
5759,
5784,
5880,
5882,
5883,
5884,
5885,
5938,
5939,
5941,
5943,
5957,
5958,
5994,
6014,
6018,
6094,
6251,
6286,
6287,
6288,
6289,
6290,
6291,
6292,
6295,
6297,
6299,
6306,
6387,
6707,
7087,
7088,
7089,
7230,
7231,
7232,
7311,
7312,
7315,
7406,
7866,
7867,
7868,
7869,
7870,
7871,
7944,
7946,
7948,
7949,
7953,
7954,
8126,
8128,
8140,
8141,
8142,
8144,
8146,
8153,
8306,
8308,
8736,
8738,
9465,
9584,
10086,
10088,
10089,
10090,
10930,
10993,
11017,
11025,
11031,
11037,
11048,
11050,
11051,
11052,
11072,
11073,
11074,
11097,
11098,
11146,
11177,
11178,
11397,
11401,
11406,
11557,
11865,
11866,
11867,
11868,
11869,
11870,
12025,
12030,
12032,
12042,
12961,
13084,
13283,
13417,
14740,
15279,
15280,
15283,
15284,
15285,
15400,
15501,
15513,
16000,
16160,
16161,
16190,
16253,
16265,
16266,
16269,
16270,
16271,
16272,
16273,
16275,
16276,
16277,
16278,
16279,
16280,
16366,
16367,
16499,
16500,
16501,
16502,
16503,
16583,
16588,
16621,
16633,
16639,
16640,
16642,
16644,
16646,
16647,
16648,
16651,
16652,
16653,
16654,
16655,
16658,
16659,
16660,
16662,
16663,
16667,
16669,
16672,
16673,
16674,
16675,
16676,
16679,
16680,
16681,
16684,
16685,
16686,
16688,
16692,
16702,
16712,
16719,
16721,
16723,
16724,
16725,
16726,
16727,
16728,
16729,
16731,
16736,
16738,
16744,
16746,
16749,
16752,
16755,
16756,
16761,
16763,
16771,
16773,
16774,
16780,
16823,
17005,
17089,
17101,
17110,
17120,
17121,
17122,
17204,
17212,
17214,
17215,
17219,
17222,
17245,
17246,
17424,
17434,
17441,
17442,
17480,
17481,
17482,
17483,
17484,
17487,
17488,
17504,
17505,
17509,
17510,
17511,
17513,
17514,
17519,
17520,
17634,
17637,
17844,
17983,
18018,
18747,
18748,
18749,
18751,
18752,
18753,
18754,
18755,
18771,
18772,
18773,
18774,
18775,
18776,
18777,
18779,
18802,
18804,
18987,
18988,
18990,
18991,
18993,
19052,
19063,
19180,
19184,
19185,
19186,
19187,
19251,
19252,
19340,
19341,
19369,
19478,
19539,
19540,
19576,
19774,
19775,
19777,
19778,
20124,
20125,
20406,
20407,
20500,
20511,
20791,
20914,
21087,
22477,
23103,
23127,
23128,
23534,
24868,
25099,
26324,
26325,
26326,
26327,
26328,
26329,
26330,
26331,
26332,
27703,
27704,
27705);


INSERT INTO `npc_trainer_greeting` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(198  , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(328  , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(331  , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(375  , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(376  , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(377  , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(459  , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(460  , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(461  , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(514  , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(543  , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(812  , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(837  , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(895  , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(906  , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(908  , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(911  , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(912  , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(913  , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(914  , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(915  , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(916  , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(917  , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(918  , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(925  , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(926  , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(927  , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(928  , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(944  , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(985  , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(986  , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(987  , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(988  , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1103 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1215 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1218 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1226 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1228 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1229 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1231 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1232 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1234 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1241 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1292 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1300 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1317 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1346 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1355 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1382 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1385 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1386 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1404 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1411 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1430 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1458 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1470 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1473 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1632 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1651 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1676 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1680 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1681 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1683 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1699 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1700 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1701 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1702 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1703 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1901 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2114 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2119 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2122 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2123 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2124 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2126 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2127 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2128 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2129 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2130 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2131 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2132 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2326 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2327 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2329 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2367 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2390 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2391 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2399 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2485 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2489 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2492 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2627 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2704 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2798 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2818 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2834 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2836 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2837 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2855 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2856 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2878 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2879 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2998 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3001 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3004 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3007 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3009 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3011 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3013 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3026 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3028 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3030 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3031 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3032 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3033 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3034 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3036 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3038 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3039 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3040 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3041 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3042 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3043 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3044 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3045 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3046 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3047 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3048 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3049 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3059 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3060 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3061 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3062 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3063 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3064 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3065 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3066 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3067 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3069 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3087 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3136 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3137 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3153 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3154 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3155 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3156 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3157 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3169 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3170 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3171 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3172 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3173 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3174 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3175 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3179 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3181 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3184 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3185 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3290 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3306 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3324 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3325 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3326 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3327 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3328 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3332 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3344 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3345 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3347 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3352 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3353 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3354 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3355 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3357 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3363 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3365 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3373 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3399 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3401 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3403 , 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3404 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3406 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3407 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3408 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3478 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3484 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3494 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3523 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3545 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3549 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3555 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3557 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3593 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3594 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3595 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3596 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3597 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3598 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3599 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3600 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3601 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3602 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3603 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3604 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3605 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3606 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3607 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3620 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3622 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3624 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3688 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3690 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3698 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3703 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3704 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3706 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3707 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3963 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3964 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3965 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3967 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4087 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4089 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4090 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4091 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4092 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4138 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4146 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4156 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4159 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4160 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4163 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4165 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4193 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4204 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4205 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4210 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4211 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4212 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4213 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4214 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4215 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4217 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4218 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4219 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4254 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4258 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4320 , '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4552 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4563 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4564 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4565 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4566 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4567 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4568 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4573 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4576 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4578 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4582 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4583 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4584 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4588 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4591 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4593 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4594 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4595 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4596 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4598 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4606 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4607 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4608 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4611 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4614 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4616 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4732 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4752 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4753 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4772 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4773 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4898 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4900 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5032 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5037 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5038 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5040 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5041 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5113 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5114 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5115 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5116 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5117 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5127 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5137 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5141 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5142 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5143 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5144 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5145 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5146 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5147 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5148 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5149 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5150 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5153 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5157 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5159 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5161 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5164 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5165 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5166 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5167 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5171 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5172 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5173 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5174 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5177 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5392 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5479 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5480 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5482 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5484 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5489 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5491 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5492 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5493 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5495 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5496 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5497 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5498 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5499 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5501 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5502 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5504 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5505 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5506 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5511 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5513 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5515 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5516 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5517 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5518 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5564 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5566 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5612 , 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5690 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5695 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5759 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5784 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5880 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5882 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5883 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5884 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5885 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5938 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5939 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5941 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5943 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5957 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5958 , 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5994 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6014 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6018 , 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6094 , 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6251 , 'Hello, warlock!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6286 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6287 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6288 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6289 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6290 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6291 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6292 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6295 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6297 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6299 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6306 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6387 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6707 , 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7087 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7088 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7089 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7230 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7231 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7232 , 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7311 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7312 , 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7315 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7406 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7866 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7867 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7868 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7869 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7870 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7871 , 'Greetings! Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7944 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7946 , 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7948 , 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7949 , 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7953 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7954 , 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8126 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8128 , 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8140 , 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8141 , 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8142 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8144 , 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8146 , 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8153 , 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8306 , 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8308 , 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8736 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8738 , 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9465 , 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9584 , 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10086, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10088, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10089, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10090, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10930, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10993, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11017, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11025, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11031, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11037, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11048, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11050, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11051, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11052, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11072, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11073, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11074, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11097, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11098, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11146, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11177, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11178, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11397, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11401, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11406, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11557, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11865, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11866, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11867, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11868, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11869, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11870, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12025, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12030, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12032, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12042, 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12961, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13084, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13283, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13417, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14740, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15279, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15280, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15283, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15284, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15285, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15400, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15501, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15513, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16000, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16160, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16161, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16190, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16253, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16265, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16266, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16269, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16270, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16271, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16272, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16273, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16275, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16276, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16277, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16278, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16279, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16280, 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16366, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16367, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16499, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16500, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16501, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16502, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16503, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16583, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16588, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16621, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16633, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16639, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16640, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16642, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16644, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16646, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16647, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16648, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16651, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16652, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16653, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16654, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16655, 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16658, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16659, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16660, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16662, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16663, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16667, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16669, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16672, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16673, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16674, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16675, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16676, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16679, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16680, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16681, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16684, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16685, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16686, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16688, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16692, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16702, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16712, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16719, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16721, 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16723, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16724, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16725, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16726, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16727, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16728, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16729, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16731, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16736, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16738, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16744, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16746, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16749, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16752, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16755, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16756, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16761, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16763, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16771, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16773, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16774, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16780, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16823, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17005, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17089, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17101, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17110, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17120, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17121, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17122, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17204, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17212, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17214, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17215, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17219, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17222, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17245, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17246, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17424, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17434, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17441, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17442, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17480, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17481, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17482, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17483, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17484, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17487, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17488, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17504, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17505, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17509, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17510, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17511, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17513, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17514, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17519, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17520, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17634, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17637, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17844, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17983, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18018, 'I can teach you how to use a fishing pole to catch fish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18747, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18748, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18749, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18751, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18752, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18753, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18754, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18755, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18771, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18772, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18773, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18774, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18775, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18776, 'Searching for herbs requires both knowledge and instinct.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18777, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18779, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18802, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18804, 'You have not lived until you have dug deep into the earth.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18987, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18988, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18990, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18991, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18993, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19052, 'With alchemy you can turn found herbs into healing and other types of potions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19063, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19180, 'It requires a steady hand to remove the leather from a slain beast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19184, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19185, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19186, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19187, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19251, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19252, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19340, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19341, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19369, 'Can I teach you how to turn the meat you find on beasts into a feast?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19478, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19539, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19540, 'Enchanting is the art of improving existing items through magic. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19576, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19774, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19775, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19777, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19778, 'Greetings!  Can I teach you how to cut preecious gems and craft jewelry?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20124, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20125, 'Care to learn how to turn the ore that you find into weapons and metal armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20406, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20407, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20500, 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20511, 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20791, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20914, 'Hello!  Can I teach you something?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(21087, 'Greetings!  Can I teach you how to turn beast hides into armor?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22477, 'Here, let me show you how to bind those wounds....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23103, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23127, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23128, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23534, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24868, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25099, 'Engineering is very simple once you grasp the basics.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26324, 'Hello, druid!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26325, 'Hello, hunter!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26326, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26327, 'Hello, paladin!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26328, 'Hello, priest!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26329, 'Hello, rogue!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26330, 'Hello, shaman!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26331, 'Hello, warlock! Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26332, 'Hello, warrior!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27703, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27704, 'Hello, mage!  Ready for some training?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27705, 'Welcome!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
